name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        platform: [iOS, tvOS, watchOS, macOS, mac-catalyst]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run swiftlint
        uses: cirruslabs/swiftlint-action@v1
        with:
          version: latest

      - name: Run xcodebuild
        run: |
          PLATFORM=${{ matrix.platform }}
          if [[ $PLATFORM == iOS ]]; then
            SDK="iphoneos"
          elif [[ $PLATFORM == tvOS ]]; then
            SDK="appletvos"
          elif [[ $PLATFORM == watchOS ]]; then
            SDK="watchos"
          else
            SDK="macosx"
          fi
          if [[ $PLATFORM == mac-catalyst ]]; then
            xcodebuild build -scheme ToastUI -destination generic/platform=macOS,variant="Mac Catalyst" -sdk "$SDK"
          else
            xcodebuild build -scheme ToastUI -destination generic/platform="$PLATFORM" -sdk "$SDK"
          fi
